export const RouteConstants = {
  root: '/',
  terms: '/company-terms',
  contact: '/contact',
  resetPassword: '/password-reset',
  resetPasswordNew: '/user/password/edit',
  login: '/login',
  signup: '/signup',
  account: '/account',
  admin: '/admin',
  notFound: '/not-found',
  dashboard: '/dashboard',
  properties: '/dashboard/?pid=properties',
  addProperty: '/dashboard/?pid=add_property&gid=properties',
  editProperty: '/dashboard/?pid=edit_property&gid=properties&id=',
  billing: '/dashboard/?pid=billing',
  leases: '/dashboard/?pid=leases',
  addLease: '/dashboard/?pid=add_lease&gid=leases',
  editLease: '/dashboard/?pid=edit_lease&gid=leases&id=',
  stripeAccounts: '/dashboard/?pid=stripe_accounts',
  addStripeAccount: '/dashboard/?pid=add_stripe_account&gid=stripe_accounts',
  editStripeAccount: '/dashboard/?pid=edit_stripe_account&gid=stripe_accounts&id=',
  messages: '/dashboard/?pid=messages',
  renterDashboard: '/renter',
  paymentMethods: '/renter/?pid=payment_methods',
  addPaymentMethod: '/renter/?pid=add_payment_method&gid=payment_methods',
  renterMessages: '/renter/?pid=messages',
  adminDashboard: '/admin',
};

export default RouteConstants;
