export const RouteConstants = {
  root: '/',
  terms: '/company-terms',
  contact: '/contact',
  resetPassword: '/password-reset',
  resetPasswordNew: '/user/password/edit',
  login: '/login',
  signup: '/signup',
  account: '/account',
  admin: '/admin',
  notFound: '/not-found',
  dashboard: '/dashboard',
  properties: '/dashboard/?pid=properties',
  addProperty: '/dashboard/?pid=add_property&gid=properties',
  editProperty: '/dashboard/?pid=edit_property&gid=properties&id=',
  maintenance: '/dashboard/?pid=maintenance',
  billing: '/dashboard/?pid=billing',
  leases: '/dashboard/?pid=leases',
  addLease: '/dashboard/?pid=add_lease&gid=leases',
  editLease: '/dashboard/?pid=edit_lease&gid=leases&id=',
  renters: '/dashboard/?pid=renters',
  logout: '/logout',
};

export default RouteConstants;
